framework:
    validation:
        mapping:
            paths:
                - "%kernel.project_dir%/config/validation/"
        email_validation_mode: html5
      # Enables validation auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        # auto_mapping:
        # App\Entity\: []
